Repository no-chris/chord-mark, pull requests merged in 2023-01, with the labels that each got.

#587 Sub beat chord durations
  packages/chord-mark-converters/README.md
  packages/chord-mark-themes/scss/themes/dark1.scss
  packages/chord-mark-themes/scss/themes/dark2.scss
  packages/chord-mark-themes/scss/themes/dark3.scss
  packages/chord-mark-themes/scss/themes/print.scss
  packages/chord-mark-themes/src/chordMarkThemes.js
  packages/chord-mark-themes/src/sampleSong2.js
  packages/chord-mark/README.md
  packages/chord-mark/src/parser/exceptions/InvalidBeatCountException.js
  packages/chord-mark/src/parser/exceptions/InvalidSubBeatGroupException.js
  packages/chord-mark/src/parser/matchers/isChordLine.js
  packages/chord-mark/src/parser/parseChordLine.js
  packages/chord-mark/src/parser/syntax.js
  packages/chord-mark/src/renderer/components/renderBarContent.js
  packages/chord-mark/src/renderer/components/renderChordLine.js
  packages/chord-mark/src/renderer/components/renderChordSymbol.js
  packages/chord-mark/src/renderer/components/renderSong.js
  packages/chord-mark/src/renderer/components/tpl/chordSymbol.js
  packages/chord-mark/src/renderer/spacers/chord/aligned.js
  packages/chord-mark/src/renderer/spacers/chord/chordLyrics.js
  packages/chord-mark/src/renderer/spacers/chord/getBeatString.js
  packages/chord-mark/src/renderer/spacers/chord/getMaxBeatsWidth.js
  packages/chord-mark/src/renderer/spacers/chord/simple.js
  packages/chord-mark/src/renderer/symbols.js
  packages/chord-mark/tests/integration/parser/parseSong.spec.js
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song3-input.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song3-output-no-sub-beats.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song3-output-sub-beats.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/renderSong.spec.js
  packages/chord-mark/tests/unit/parser/exceptions/InvalidBeatCountException.spec.js
  packages/chord-mark/tests/unit/parser/exceptions/InvalidSubBeatGroupException.spec.js
  packages/chord-mark/tests/unit/parser/matchers/isChordLine.spec.js
  packages/chord-mark/tests/unit/parser/parseChordLine.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderBarContent.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderChordSymbol.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderSong.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/aligned.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/chordLyrics.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/getBeatString.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/getMaxBeatsWidth.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/simple.spec.js
  packages/documentation/docs/reference/chords.mdx
Labels: enhancement

#592 Time signature in chord line
  packages/chord-mark-converters/README.md
  packages/chord-mark/src/parser/exceptions/InvalidBarRepeatException.js
  packages/chord-mark/src/parser/matchers/isChordLine.js
  packages/chord-mark/src/parser/parseChordLine.js
  packages/chord-mark/src/parser/syntax.js
  packages/chord-mark/src/renderer/components/renderBarContent.js
  packages/chord-mark/src/renderer/components/renderChordLine.js
  packages/chord-mark/src/renderer/components/renderSong.js
  packages/chord-mark/src/renderer/spacers/chord/aligned.js
  packages/chord-mark/src/renderer/spacers/chord/chordLyrics.js
  packages/chord-mark/src/renderer/spacers/chord/getMaxBeatsWidth.js
  packages/chord-mark/src/renderer/spacers/chord/simple.js
  packages/chord-mark/src/renderer/symbols.js
  packages/chord-mark/tests/integration/parser/parseSong.spec.js
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song4-input.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song4-output-inline-time-signatures.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song4-output-no-inline-time-signatures.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/renderSong.spec.js
  packages/chord-mark/tests/unit/parser/exceptions/InvalidBarRepeatException.spec.js
  packages/chord-mark/tests/unit/parser/matchers/isChordLine.spec.js
  packages/chord-mark/tests/unit/parser/parseChordLine.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderBarContent.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderChordLine.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderSong.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/aligned.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/chordLyrics.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/getMaxBeatsWidth.spec.js
  packages/documentation/docs/reference/chords.mdx
Labels: enhancement

#596 Fix the position of the first chord of a bar
  packages/chord-mark-converters/tests/converters/chordMark2UltimateGuitar/chordMark2UltimateGuitar.spec.js
  packages/chord-mark/src/renderer/components/renderChordLine.js
  packages/chord-mark/src/renderer/components/renderSong.js
  packages/chord-mark/src/renderer/spacers/chord/chordLyrics.js
  packages/chord-mark/src/renderer/spacers/chord/getBeatString.js
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song1-output-default.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song1-output-grids-bar-sep.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song1-output-no-bar-sep.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song1-output-transposed.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song2-output-copy-and-multiply.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song2-output-copy.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song2-output-multiply.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song2-output-no-copy-no-multiply.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song3-output-no-sub-beats.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song3-output-sub-beats.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song4-output-inline-time-signatures.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song4-output-no-inline-time-signatures.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/renderSong.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderChordLine.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderSong.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/chordLyrics.spec.js
Labels: enhancement

#586 Added Boxes Theme SCSS
  packages/chord-mark-themes/scss/chordMarkThemes.scss
  packages/chord-mark-themes/scss/themes/print2.scss
  packages/chord-mark-themes/src/chordMarkThemes.js
  packages/chord-mark/README.md
  packages/chord-mark/lib/chord-mark.js
  packages/chord-mark/lib/chord-mark.js.map
  packages/chord-mark/src/renderer/components/renderLine.js
  packages/chord-mark/src/renderer/components/renderSong.js
  packages/chord-mark/src/renderer/components/tpl/line.js
  packages/chord-mark/tests/unit/renderer/components/renderLine.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderSong.spec.js
Labels: breaking

#597 Fix the position of the first chord of a sub-beat group
  packages/chord-mark/src/renderer/spacers/chord/chordLyrics.js
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song3-output-sub-beats.txt
  packages/chord-mark/tests/unit/renderer/components/renderSong.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/chordLyrics.spec.js
Labels: enhancement

#598 Change sub beat delimiters to square brackets
  packages/chord-mark-themes/scss/themes/dark1.scss
  packages/chord-mark-themes/scss/themes/dark2.scss
  packages/chord-mark-themes/scss/themes/dark3.scss
  packages/chord-mark-themes/scss/themes/print.scss
  packages/chord-mark-themes/scss/themes/print2.scss
  packages/chord-mark/src/parser/parseChordLine.js
  packages/chord-mark/src/parser/syntax.js
  packages/chord-mark/src/renderer/symbols.js
  packages/chord-mark/tests/integration/parser/parseSong.spec.js
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song3-input.txt
  packages/chord-mark/tests/integration/renderer/components/renderSong/data/song3-output-sub-beats.txt
  packages/chord-mark/tests/unit/parser/matchers/isChordLine.spec.js
  packages/chord-mark/tests/unit/parser/parseChordLine.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderBarContent.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderChordLine.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderChordSymbol.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderSong.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/aligned.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/chordLyrics.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/getBeatString.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/getMaxBeatsWidth.spec.js
  packages/chord-mark/tests/unit/renderer/spacers/chord/simple.spec.js
  packages/documentation/docs/reference/chords.mdx
  packages/documentation/package.json
Labels: enhancement

#599 change packages entry point to unbundled versions
  packages/chord-mark-converters/package.json
  packages/chord-mark-themes/package.json
  packages/chord-mark/package.json
Labels: breaking

#600 Recognise key declarations to automatically set accidentals
  packages/chord-mark-converters/package.json
  packages/chord-mark-converters/yarn.lock
  packages/chord-mark-themes/scss/themes/dark1.scss
  packages/chord-mark-themes/scss/themes/dark2.scss
  packages/chord-mark-themes/scss/themes/dark3.scss
  packages/chord-mark-themes/scss/themes/print.scss
  packages/chord-mark-themes/scss/themes/print2.scss
  packages/chord-mark/package.json
  packages/chord-mark/src/parser/getAllChordsInSong.js
  packages/chord-mark/src/parser/getAllKeysInSong.js
  packages/chord-mark/src/parser/helper/keyHelpers.js
  packages/chord-mark/src/parser/lineTypes.js
  packages/chord-mark/src/parser/matchers/isKeyDeclaration.js
  packages/chord-mark/src/parser/matchers/isSectionLabel.js
  packages/chord-mark/src/parser/parseKeyDeclaration.js
  packages/chord-mark/src/parser/parseSectionLabel.js
  packages/chord-mark/src/parser/parseSong.js
  packages/chord-mark/src/parser/songLinesFactory.js
  packages/chord-mark/src/parser/syntax.js
  packages/chord-mark/src/renderer/components/renderKeyDeclaration.js
  packages/chord-mark/src/renderer/components/renderSong.js
  packages/chord-mark/src/renderer/components/tpl/keyDeclaration.js
  packages/chord-mark/src/renderer/symbols.js
  packages/chord-mark/tests/integration/parser/parseSong.spec.js
  packages/chord-mark/tests/unit/parser/getAllChordsInSong.spec.js
  packages/chord-mark/tests/unit/parser/getAllKeysInSong.spec.js
  packages/chord-mark/tests/unit/parser/helpers/keyHelpers.spec.js
  packages/chord-mark/tests/unit/parser/matchers/isKeyDeclaration.spec.js
  packages/chord-mark/tests/unit/parser/matchers/isSectionLabel.spec.js
  packages/chord-mark/tests/unit/parser/parseKeyDeclaration.spec.js
  packages/chord-mark/tests/unit/parser/parseSong.spec.js
  packages/chord-mark/tests/unit/parser/songLinesFactory.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderKeyDeclaration.spec.js
  packages/chord-mark/tests/unit/renderer/components/renderSong.spec.js
  packages/chord-mark/yarn.lock
  packages/documentation/docs/reference/keys.mdx
  packages/documentation/sidebars.js
Labels: enhancement, breaking
